[package]
name = "stb_truetype"
version = "0.2.1"
authors = ["Dylan Ede <dylanede@googlemail.com>"]
description = "A straight translation of the font loading code in stb_truetype.h from C to Rust."
documentation = "https://dylanede.github.io/stb_truetype-rs"
homepage = "https://github.com/dylanede/stb_truetype-rs"
repository = "https://github.com/dylanede/stb_truetype-rs"
readme = "README.md"
license = "MIT / Apache-2.0"
keywords = ["font", "truetype", "opentype", "ttf", "otf"]

[dependencies]
byteorder = { version = "1.0.0", default-features = false }
